title: Asch Docs
subtitle: ""
description: ""
author: Asch
language: zh-cn
timezone: UTC

url: http://docs.asch.mobi
root: /
permalink: news/:year/:month/:day/:title/
code_dir: downloads/code
per_page: 0

theme: navy

highlight:
  enable: true
  line_number: false

algolia:
  en:
    api_key: f5f22910bc3027dabc0b1bdafa88cb42
    index_name: asch
  zh-cn:
    api_key: f5f22910bc3027dabc0b1bdafa88cb42
    index_name: asch
github: AschPlatform/asch
